### ISSUE TITLE
May I ask how do your render the content to view?

### ISSUE THREAD

**Issue by lqminh2207** [hunghg255/reactjs-tiptap-editor#106]

**Comment by hunghg255** [comment]
you can check this https://www.w3schools.com/jsref/met_node_insertadjacenthtml.asp

**Comment by lqminh2207** [comment]
@hunghg255 I found that on original lib has read-only instance. I can't find it in your lib. Do you have it?

https://tiptap.dev/docs/guides/output-json-html#render

![image](https://github.com/user-attachments/assets/31074d2b-519d-42e6-982a-8ae5bcc70bd7)

**Comment by hunghg255** [comment]
> @hunghg255 I found that on original lib has read-only instance. I can't find it in your lib. Do you have it?
> 
> [tiptap.dev/docs/guides/output-json-html#render](https://tiptap.dev/docs/guides/output-json-html#render)
> 
> ![image](https://private-user-images.githubusercontent.com/93562814/384271396-31074d2b-519d-42e6-982a-8ae5bcc70bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTIzOTUsIm5iZiI6MTczMTA1MjA5NSwicGF0aCI6Ii85MzU2MjgxNC8zODQyNzEzOTYtMzEwNzRkMmItNTE5ZC00MmU2LTk4MmEtOGFlNWJjYzcwYmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA3NDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTYxNmJiM2I3Yjk2M2E0MWI5ZTA2NGYzOTY3Y2JhMThhNmQ3OWIyY2JmNDE1NWYyMGM5N2RhZGJjMTVhY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gCu2KGZivjhTj7wpMS69EsPq-aA2NSh5i1kMIBaLn5o)

https://reactjs-tiptap-editor.vercel.app/guide/customize.html#_3-accessing-the-editor-instance
you can refer this

**Comment by lqminh2207** [comment]
I tried to set editable to false. But It seem only content is disabled and toolbar doesn't disappear 
![image](https://github.com/user-attachments/assets/d8280885-1768-40b7-a22b-c073b221db15)

**Comment by hunghg255** [comment]
im not sure, can you create a repo, I will check help you

**Comment by lqminh2207** [comment]
@hunghg255 What do you think about create new feature for read-only mode? 
Currently after save data then display that data it doesn't same as when we comment, I think because of CSS.

**Comment by lqminh2207** [comment]
@hunghg255 Like on your playground. If using these HTML to display then content will not be the same on the editor
![image](https://github.com/user-attachments/assets/2d200d44-6152-490b-af5e-aa3a7f9e8bc3)

**Comment by hunghg255** [comment]
> @hunghg255 What do you think about create new feature for read-only mode? 
> 
> Currently after save data then display that data it doesn't same as when we comment, I think because of CSS.

yea. pull request welcome

**Comment by M4rdine** [comment]
@lqminh2207 Hey, how did you make this work? I have the same context of having to render the content saved in another repository, but the css is getting lost in this... how are you doing to render the content to view?
