### ISSUE TITLE
Feature Request: The content of the bubble menu is customizable

### ISSUE THREAD

**Issue by condorheroblog** [hunghg255/reactjs-tiptap-editor#11]
For example, when my rich text editor doesn't require the `Code` extension, the code should run smoothly. However, there are currently errors because the content of the bubble menu is hardcoded and must be initialized.

<img width="754" alt="image" src="https://github.com/user-attachments/assets/123dbc7a-9155-4ed0-a2b5-515272122702">

```js
{!props?.hideBubble && (
    <>
      <ColumnsMenu editor={editor} />
      <TableBubbleMenu editor={editor} />
      <ContentMenu editor={editor} disabled={props?.disabled} />

      <BubbleMenuLink editor={editor} disabled={props?.disabled} />
      <BubbleMenuText editor={editor} disabled={props?.disabled} />
      <BubbleMenuImage editor={editor as any} disabled={props?.disabled} />
      <BubbleMenuVideo editor={editor as any} disabled={props?.disabled} />
    </>
  )}
```

---

I think we should add a parameter similar to 'toolbar', perhaps called 'bubble'.

```ts
export interface GeneralOptions<T> {
  /** Enabled divider */
  divider: boolean;
  /** Enabled spacer */
  spacer: boolean;
  /** Button view function */
  button: ButtonView<T>;
  /** Show on Toolbar */
  toolbar?: boolean;
  /** Show on Bubble Menu */
  bubble?: boolean;
}
```

I've been researching this, but it's not finished yet. I'm also not very certain about some of the effects. What's your opinion?😂

**Comment by hunghg255** [comment]
@condorheroblog I think we can try dynamic like this. 

```ts
const bubbleList = ['bold', 'italic', 'underline', 'strike', 'code', 'link', 'divider', 'color', 'highlight']

export function getBubbleText(editor: Editor, t: any) {
  const bubbleMenu = bubbleList.filter((type) => {
    if (type === 'divider') {
      return true
    }

    const ext = editor.extensionManager.extensions.find((ext: any) => ext.name === type)
    return !!ext
  }).map((it) => {
    const ext: any = editor.extensionManager.extensions.find((ext: any) => ext.name === it)
    if (it === 'divider') {
      return {
        type: 'divider',
        component: undefined,
        componentProps: {},
      }
    }

    return ext.configure().options.button({ editor, t } as any)
  })

  return bubbleMenu
}

```

**Comment by hunghg255** [comment]
I understand your error, if we are not import extension when initial editor, 
we can not use extension in bubble menu

**Comment by condorheroblog** [comment]
Yes, no import no UI🤔

**Comment by hunghg255** [comment]
> Yes, no import no UI🤔

yes, I think it oke.

if want to show code on the bubble, we need to import Code extension to BaseKit and hide it

**Comment by hunghg255** [comment]
or we can pass config toolbar to extension to hide/show extension icon on toolbar
```diff
export const Code = TiptapCode.extend<CodeOptions>({
  addOptions() {
    return {
      ...this.parent?.(),
+      toolbar: false,
      button: ({ editor, t }) => ({
        component: ActionButton,
        componentProps: {
          action: () => editor.commands.toggleCode(),
          isActive: () => editor.isActive('code') || false,
          disabled: !editor.can().toggleCode(),
          icon: 'Code',
          shortcutKeys: ['mod', 'E'],
          tooltip: t('editor.code.tooltip'),
        },
      }),
    }
  },
})
```

**Comment by hunghg255** [comment]
@condorheroblog ah you mean, We can make bubble menu dynamic content, currently I am hardcoding the content of the bubble. ok. We will think of ways to make your thing happen

**Comment by condorheroblog** [comment]
I think you understand what I mean is.

---

The ability to flexibly configure this feature is really exciting. The toolbar is even more commonly used. The plugin could support a standard mode, and then expose an API that exports all toolbar components to the user. Users could then customize the order and integration of these components. For example, users could implement a simplified mode.

<img width="1326" alt="image" src="https://github.com/user-attachments/assets/52854121-c711-4e61-a78c-42b2de50f41e">

<img width="1252" alt="image" src="https://github.com/user-attachments/assets/42f24af9-97f1-4553-8c98-185003b06c46">

**Comment by hunghg255** [comment]
so I think we need to have a step before showing icon (this step to add extension to editor)  after that we can show/hide extension on toolbar menu or bubble menu.
