### ISSUE TITLE
Tooltips overlap due to animate-out

### ISSUE THREAD

**Issue by Pingvin0** [hunghg255/reactjs-tiptap-editor#111]
When going from a tooltip on the right to one on the left, the animate-out property causes the tooltips to overlap, which is very disorienting.
![image](https://github.com/user-attachments/assets/c551ca5e-0416-4968-8e32-9c4a8be330ae)

Removing `data-[state=closed]:richtext-animate-out data-[state=closed]:richtext-fade-out-0 data-[state=closed]:richtext-zoom-out-95` from tooltip.tsx fixes this, and the remaining default animations are faster and smoother, which make the editor feel nicer to use in my opinion.

**Comment by hunghg255** [comment]
I updated
