### ISSUE TITLE
[Bug]: add video as link 

### ISSUE THREAD

**Issue by waleedsalah4** [hunghg255/reactjs-tiptap-editor#112]
Trying to add a video link as in this picture

![Screenshot (7)](https://github.com/user-attachments/assets/5c92474d-62bf-4b6e-8e14-a573f043609e)

and press apply

![Screenshot (8)](https://github.com/user-attachments/assets/99517539-b000-42f1-9d94-2b883305d8e2)
the video is shown as expected, but submit the form and save the content to local storage
and try to reload the page, and the initial content for the editor will be that data saved into local storage, 
I got this weird form inside the editor

![Screenshot (9)](https://github.com/user-attachments/assets/f8c35080-3208-4f95-8a75-cc7b95e28e2c)

you can find the code here and see issue

[check the code on stackblitz](https://stackblitz.com/edit/vitejs-vite-dujwxg?file=src%2FApp.tsx,src%2FApp.css&terminal=dev)

**Comment by hunghg255** [comment]
@waleedsalah4 can you record a video for this bug?

**Comment by waleedsalah4** [comment]
Here's a recorded video for the bug

https://github.com/user-attachments/assets/5f0252ea-5fa8-4259-ba79-f10830590b81

**Comment by hunghg255** [comment]
> Here's a recorded video for the bug
> 
>  VID_20241117_191242.mp4

oke, this is a bug, we need to validate the video when submit, We only accept link video format mp4, mov,..

**Comment by waleedsalah4** [comment]
Still can't add a YouTube video or other links and prevent men from pasting the url into the field and gives invalid url 

But when I past a link that ends with .mp4 or other supported formats by the editor it adds it 
So l, I think this an issue that need to be fixed and allow user to add there own video links like YouTube ones

https://github.com/user-attachments/assets/d653dc05-df16-4330-9966-07213f5e737b

**Comment by hunghg255** [comment]
you should use iframe to add link youtube
