### ISSUE TITLE
NextJS - ReferenceError: CustomEvent is not defined 

### ISSUE THREAD

**Issue by mnhtrieu** [hunghg255/reactjs-tiptap-editor#116]
Hello when trying to use this package it says to me: 

```
ReferenceError: CustomEvent is not defined
```

Not sure where is it from and what to do. I searched in the repo and CustomEvent was found in SearchAndReplace extension which I don't even use.

The whole file is:

```
"use client"

import RichTextEditor, {
  BaseKit, Blockquote,
  Bold,
  BulletList, Clear,
  en,
  Heading,
  History,
  HorizontalRule,
  Indent,
  Italic,
  Link,
  locale, OrderedList,
  Strike, TextAlign,
  Underline
} from 'reactjs-tiptap-editor';

import 'reactjs-tiptap-editor/style.css';

const extensions = [
  BaseKit.configure({
    characterCount: false,
  }),
  Heading,
  Bold,
  Italic,
  Underline,
  Strike,
  TextAlign,
  BulletList,
  OrderedList,
  Link,
  HorizontalRule,
  History,
  Indent,
  Blockquote,
  Clear,
];

export default function Editor({value, setValue}: { value: string, setValue: (val: string) => void }) {

  return (
    <RichTextEditor
      output='html'
      content={value}
      onChangeContent={setValue}
      extensions={extensions}
      bubbleMenu={{
        floatingMenuConfig: {
          hidden: true,
        }
      }}
    />
  );
}
```

does anybody know what should i do or which extension does this?

**Comment by hunghg255** [comment]
@mnhtrieu can you send me a repo? Which browser are you using?

**Comment by mnhtrieu** [comment]
I added you as collaborator. I created a separe project, without the code surrounding just the usage of the editor and their related pages. 

I also left out the same dependencies. 

It happens in the github actions, however when building on my mac `next build` it builds correctly. Just inside the github actions it crashed. You can check out the latest job run.

hope I provided everything for you as I'm not sure what is wrong and dunno what more can I provide

**Comment by hunghg255** [comment]
![Screenshot 2024-11-25 at 15 18 40](https://github.com/user-attachments/assets/799d8689-a730-490c-995c-81d0647b6894)
CustomEvent is API from the browser, when the next build is prerending, it runs on the server (node env), and it will throw an error.

you can try import dynamic components use option SSR: false

**Comment by mnhtrieu** [comment]
Oh yea sorry... when I wrote this issue I tried to adjust it afterwards and I did try importing it dynamically. But still says the same

<img width="809" alt="image" src="https://github.com/user-attachments/assets/f7591bef-abae-4c65-ab46-a5f9a6efa8a5">

**Comment by hunghg255** [comment]
> Oh yea sorry... when I wrote this issue I tried to adjust it afterwards and I did try importing it dynamically. But still says the same
> 
> <img alt="image" width="809" src="https://private-user-images.githubusercontent.com/14034755/389438499-f7591bef-abae-4c65-ab46-a5f9a6efa8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjQ4MDMsIm5iZiI6MTczMjUyNDUwMywicGF0aCI6Ii8xNDAzNDc1NS8zODk0Mzg0OTktZjc1OTFiZWYtYWJhZS00YzY1LWFiNDYtYTVmOWE2ZWZhOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA4NDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNDM5NzljZTI3ZTQ2ODNhMTZiYTViN2FhYTk3NGY5M2JjNjk2MzM2N2MyOWViYjdlMDM2NWY4YjcwYjA2ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2E2S9H1b42a0SrSpXpwgN4LBYMpQyoHtB0vG82Z1WE8">

nope, do you understand about nextjs working

you should import all components instead of for library

in this page `src/app/admin/(panel)/blogs/create/page.tsx`

```diff
- import Editor from "~/app/admin/(panel)/components/editor";
import {useState} from "react";
+ import dynamic from 'next/dynamic';

+ const Editor = dynamic(() => import("~/app/admin/(panel)/components/editor"), { ssr: false })
```

**Comment by mnhtrieu** [comment]
oh... my bad... I understood you wrong. Thank you very much. Solved.
