### ISSUE TITLE
Feature Request: Export a PDF file

### ISSUE THREAD

**Issue by condorheroblog** [hunghg255/reactjs-tiptap-editor#14]
Do you have any good ideas? 

What I can think of now is to generate an HTML content and then export it to PDF

**Comment by hunghg255** [comment]
we can create a new extension for exporting pdf,
same idea as you, can we use Puppeteer open page after exporting the PDF? or are you know any package supports HTML string to PDF

**Comment by condorheroblog** [comment]
Puppeteer is excellent, but as far as I know, it runs on the server-side. What we need is to generate PDFs on the client-side. I tried [https://github.com/eKoopmans/html2pdf.js](https://github.com/eKoopmans/html2pdf.js), but the results were very unsatisfactory, and it's not possible to copy text from the generated PDF.

It is a big problem.🤔

**Comment by hunghg255** [comment]
we can use try this lib: https://www.npmjs.com/package/@progress/kendo-drawing
