### ISSUE TITLE
[Bug] The style coverage is too broad

### ISSUE THREAD

**Issue by condorheroblog** [hunghg255/reactjs-tiptap-editor#28]
```css
@import "reactjs-tiptap-editor/style.css";
```

When I introduced the editor's style, my application had a little style confusion.

I checked the content of `reactjs-tiptap-editor/style.css` and found that it was affected by the [preset style of `tailwind.css`](https://tailwindcss.com/docs/preflight#disabling-preflight). Here I want to extract a problem. The style of tailwind.css has too large an impact. 

Maybe we should use CSS in JS solutions or manually manage class names, such as
https://github.com/xyflow/xyflow/blob/9b768b2dae9f046c4c10772b267ad3116c3333a5/packages/react/package.json#L45

**Comment by hunghg255** [comment]
@condorheroblog oke, I got it, I will refactor and add a prefix to the class.

**Comment by condorheroblog** [comment]
Which one do you like, CSS in JS or BEM😁

**Comment by hunghg255** [comment]
> Which one do you like, CSS in JS or BEM😁

ah. Im still use tailwindcss. but I add prefix class

**Comment by hunghg255** [comment]
I updated and added the prefix class,

**Comment by condorheroblog** [comment]
Sorry, my problem is still not solved.

The reason is that `tailwind.css` will package a preset style - https://tailwindcss.com/docs/preflight#disabling-preflight, and the CSS in it is global.

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/0b1b48a3-9e65-48a4-906d-a2c4596f766c">


 I think `reactjs-tiptap-editor`, as a plugin, has no reason to change the user's global CSS style.

Also, the style names of `tailwind.css` are very simple, which is very likely to conflict with the user's type. It would be fine if all styles can have a prefix classname.

**Comment by hunghg255** [comment]
@condorheroblog oke, let me try, yesterday I tried disabling preflight, and UI is like the 90s =))
I think because I do not add a prefix to the class yet

**Comment by hunghg255** [comment]
@condorheroblog you can try install a new version, I hope it works as well

**Comment by hunghg255** [comment]
![Screenshot 2024-08-21 at 10 21 59](https://github.com/user-attachments/assets/fac18e93-5693-40c7-915f-c0acda0f09b6)

oh. =))) look this xD

**Comment by condorheroblog** [comment]
It looks weird, maybe we need to use https://www.radix-ui.com/themes/docs/components/button to replace the native button

**Comment by hunghg255** [comment]
shadcn is using the native button.
btw can you screenshot editor on your project, I want to see it look how
maybe I will add a props resets CSS to load the reset CSS file or not, because the editor needs to reset CSS to it display with style from editor instead of use the global CSS of app

**Comment by condorheroblog** [comment]
It looks like that.

<img width="1185" alt="image" src="https://github.com/user-attachments/assets/866a7ba8-d8e2-44c6-982e-fa32a05282bd">

**Comment by hunghg255** [comment]
@condorheroblog yea, the same, 
https://reactjs-tiptap-editor-playground.vercel.app/

**Comment by hunghg255** [comment]
> It looks like that.
> 
> <img alt="image" width="1185" src="https://private-user-images.githubusercontent.com/47056890/359742358-866a7ba8-d8e2-44c6-982e-fa32a05282bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTQzMjEsIm5iZiI6MTcyNDIxNDAyMSwicGF0aCI6Ii80NzA1Njg5MC8zNTk3NDIzNTgtODY2YTdiYTgtZDhlMi00NGM2LTk4MmUtZmEzMmEwNTI4MmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA0MjAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMzgzNjA4ZDZiNzllM2I5ZmM2NmVmZWIyMjI1NjdhZWZmYTMzZWE3N2RmNTE0ZmZmODIyMGY3NTg4ODU4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uDVUK6aEDLoOlm7cnDzEkgSJGFVPdlsmYBN7rkrhC_A">

I update the style. you can install the latest version.

**Comment by condorheroblog** [comment]
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/8e892131-5105-4190-84f4-7667dff0593f">


You Rock, Thanks👍

**Comment by hunghg255** [comment]
> <img alt="image" width="1255" src="https://private-user-images.githubusercontent.com/47056890/360282744-8e892131-5105-4190-84f4-7667dff0593f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDI1MTUsIm5iZiI6MTcyNDMwMjIxNSwicGF0aCI6Ii80NzA1Njg5MC8zNjAyODI3NDQtOGU4OTIxMzEtNTEwNS00MTkwLTg0ZjQtNzY2N2RmZjA1OTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA0NTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3M2Q0Njk5YjU1NzMwYThiYzVmMzk0YWZmN2RkMmRjNzQ2OWRmMmY2YzY5NzUzNDA1MDYzYTVkZjU3MGZkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WoOIs4UiQhilTpsgg7q3-49z39K5lUWs6Kx5QAcpGTM">
> You Rock, Thanks👍

"Looks great! I hope it works just as well."

**Comment by condorheroblog** [comment]
I'm very sorry, I'll leave a message again.

I use antd in my project, some buttons are so weird.

![image](https://github.com/user-attachments/assets/19b7f497-8fe0-46de-a701-427c77ec5dbc)

I saw some global CSS

<img width="878" alt="image" src="https://github.com/user-attachments/assets/e5b8c467-3d45-4f72-86fd-9b39279c2edf">

Developing a component library using `tailwind.css` is a real headache problem. I like BEM 😂

**Comment by hunghg255** [comment]
@condorheroblog I remove css global. you can check again now
