### ISSUE TITLE
[Bug]The text jumps

### ISSUE THREAD

**Issue by condorheroblog** [hunghg255/reactjs-tiptap-editor#30]
Hello, Good evening!

![2024-08-22 18 11 41](https://github.com/user-attachments/assets/165a8f65-94e0-439f-85a8-370313cbde00)

When I add fonts to selected text, the text changes fonts first, then resets fonts. 

Normally, the whole process should be static.

**Comment by hunghg255** [comment]
> Hello, Good evening!
> 
> ![2024-08-22 18 11 41](https://private-user-images.githubusercontent.com/47056890/360388359-165a8f65-94e0-439f-85a8-370313cbde00.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjI1MTksIm5iZiI6MTcyNDMyMjIxOSwicGF0aCI6Ii80NzA1Njg5MC8zNjAzODgzNTktMTY1YThmNjUtOTRlMC00MzlmLTg1YTgtMzcwMzEzY2JkZTAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5M2M2ZTUzNWU0ZDQwYjBiZmExOGQ5NTI3NjIyNWIzMmEzNDc2NzY2ZjdjOWFkZGM5ZGQxZTEzYjk3OTc2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kCuNebIjl5486EFE9OizeUPAU0pXaVTrvIsucccu4Ls) [ ![2024-08-22 18 11 41](https://private-user-images.githubusercontent.com/47056890/360388359-165a8f65-94e0-439f-85a8-370313cbde00.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjI1MTksIm5iZiI6MTcyNDMyMjIxOSwicGF0aCI6Ii80NzA1Njg5MC8zNjAzODgzNTktMTY1YThmNjUtOTRlMC00MzlmLTg1YTgtMzcwMzEzY2JkZTAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5M2M2ZTUzNWU0ZDQwYjBiZmExOGQ5NTI3NjIyNWIzMmEzNDc2NzY2ZjdjOWFkZGM5ZGQxZTEzYjk3OTc2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kCuNebIjl5486EFE9OizeUPAU0pXaVTrvIsucccu4Ls) ](https://private-user-images.githubusercontent.com/47056890/360388359-165a8f65-94e0-439f-85a8-370313cbde00.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjI1MTksIm5iZiI6MTcyNDMyMjIxOSwicGF0aCI6Ii80NzA1Njg5MC8zNjAzODgzNTktMTY1YThmNjUtOTRlMC00MzlmLTg1YTgtMzcwMzEzY2JkZTAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5M2M2ZTUzNWU0ZDQwYjBiZmExOGQ5NTI3NjIyNWIzMmEzNDc2NzY2ZjdjOWFkZGM5ZGQxZTEzYjk3OTc2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kCuNebIjl5486EFE9OizeUPAU0pXaVTrvIsucccu4Ls) [ ](https://private-user-images.githubusercontent.com/47056890/360388359-165a8f65-94e0-439f-85a8-370313cbde00.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjI1MTksIm5iZiI6MTcyNDMyMjIxOSwicGF0aCI6Ii80NzA1Njg5MC8zNjAzODgzNTktMTY1YThmNjUtOTRlMC00MzlmLTg1YTgtMzcwMzEzY2JkZTAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5M2M2ZTUzNWU0ZDQwYjBiZmExOGQ5NTI3NjIyNWIzMmEzNDc2NzY2ZjdjOWFkZGM5ZGQxZTEzYjk3OTc2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kCuNebIjl5486EFE9OizeUPAU0pXaVTrvIsucccu4Ls)
> 
> When I add fonts to selected text, the text changes fonts first, then resets fonts.
> 
> Normally, the whole process should be static.

good evening too, yea I know this, it is related to CSS reset, I just update you can try latest version

**Comment by condorheroblog** [comment]
Perfect 👍
