### ISSUE TITLE
[Perf] Optimize the size

### ISSUE THREAD

**Issue by condorheroblog** [hunghg255/reactjs-tiptap-editor#36]
React Tiptap Editor is 11MB in size after bundling.

<img width="1708" alt="image" src="https://github.com/user-attachments/assets/90fd9443-7b7f-4ffe-b84f-6286fcddf974">

**Comment by hunghg255** [comment]
@condorheroblog yea, I see, vendor file is heavy

**Comment by hunghg255** [comment]
![Screenshot 2024-08-27 at 11 42 15](https://github.com/user-attachments/assets/71fc20e0-b4f0-409e-a5e8-b6bce86279ec)
I will move shiki and katex to external library

**Comment by hunghg255** [comment]
@condorheroblog can you install the latest version. hope bundle size is smaller

**Comment by condorheroblog** [comment]
Good Job👍

<img width="561" alt="image" src="https://github.com/user-attachments/assets/58337e6d-4ecd-4a6f-a7d5-e9b17acec790">

---
But I don't know why the vendor file is still a little bit bigger.😂
<img width="1326" alt="image" src="https://github.com/user-attachments/assets/834daeb5-ae5a-43ef-a4b4-0ebdba2859e3">

**Comment by hunghg255** [comment]
yea. we have many dependencies. I will check later.
