### ISSUE TITLE
[Bug]When rendering the image, an empty `img` tag is added

### ISSUE THREAD

**Issue by condorheroblog** [hunghg255/reactjs-tiptap-editor#38]
Check This Demo Link: https://reactjs-tiptap-editor-playground.vercel.app/

<img width="1675" alt="image" src="https://github.com/user-attachments/assets/d1b248ca-86bc-47e7-a965-0105bf36c8d2">

**Comment by hunghg255** [comment]
@condorheroblog I fixed this bug, move to use block instead of inline

**Comment by hunghg255** [comment]
![Screenshot 2024-09-07 at 09 04 03](https://github.com/user-attachments/assets/d7cf84d5-e2dc-46d5-bb7c-c6122f541fc2)
