### ISSUE TITLE
Something wrong with Task List Extension

### ISSUE THREAD

**Issue by mcnaveen** [hunghg255/reactjs-tiptap-editor#42]
Hey there, This is an awesome project. Good work 🫡

I'm thinking of using this in my upcoming project and I just found a bug. See how the Task list is rendering.

I made a video of it.

https://github.com/user-attachments/assets/6b7d6794-912c-42d1-ba2d-475b885b4831

**Comment by hunghg255** [comment]
> Hey there, This is an awesome project. Good work 🫡
> 
> I'm thinking of using this in my upcoming project and I just found a bug. See how the Task list is rendering.
> 
> I made a video of it.
> 
>  tiptap-shadcn-bug.mp4

thanks you for your feedback, I will check this bug

**Comment by hunghg255** [comment]
@mcnaveen I fixed this issue. you can install latest version
