### ISSUE TITLE
Support for attach files

### ISSUE THREAD

**Issue by JohnnyDevJs** [hunghg255/reactjs-tiptap-editor#45]
Is there a block for uploading files?

**Comment by hunghg255** [comment]
Currently there is no extension support for attaching files. I will reseach later

**Comment by hunghg255** [comment]
@JohnnyDevJs I added an extension to the attachment

**Comment by JohnnyDevJs** [comment]
@hunghg255 I saw the new fit, it looks really good. Thanks!
