### ISSUE TITLE
ImageUpload configure

### ISSUE THREAD

**Issue by JohnnyDevJs** [hunghg255/reactjs-tiptap-editor#49]
Don't return blob, return image and save image to a folder.

<img width="989" alt="Captura de Tela 2024-10-01 às 12 43 02" src="https://github.com/user-attachments/assets/d0d98cf9-ccc5-4dc9-b5ee-e2c68249aabb">

**Comment by hunghg255** [comment]
@JohnnyDevJs Yeah, it is an example so I used to blob
you can refer to the docs, and pass your service 
https://reactjs-tiptap-editor.vercel.app/extensions/ImageUpload/#usage

**Comment by hunghg255** [comment]
> I'm new to programming, could you help me? Return the image in base64.

do you have an API to upload image files?

**Comment by JohnnyDevJs** [comment]
> > I'm new to programming, could you help me? Return the image in base64.
> 
> do you have an API to upload image files?

yes I have.

**Comment by JohnnyDevJs** [comment]
> > > I'm new to programming, could you help me? Return the image in base64.
> > 
> > 
> > do you have an API to upload image files?
> 
> yes I have.

I noticed that when I load and save content the image remains for a while and then disappears. using the blob, if there is a way for the images to remain using the blob, we can keep it.

**Comment by hunghg255** [comment]
> > > > I'm new to programming, could you help me? Return the image in base64.
> > > 
> > > 
> > > do you have an API to upload image files?
> > 
> > 
> > yes I have.
> 
> I noticed that when I load and save content the image remains for a while and then disappears. using the blob, if there is a way for the images to remain using the blob, we can keep it.

can you can share me a repo, it will easy to debug

**Comment by JohnnyDevJs** [comment]
Yes, one moment that i go to send.

**Comment by JohnnyDevJs** [comment]
> > > > > I'm new to programming, could you help me? Return the image in base64.
> > > > 
> > > > 
> > > > do you have an API to upload image files?
> > > 
> > > 
> > > yes I have.
> > 
> > 
> > I noticed that when I load and save content the image remains for a while and then disappears. using the blob, if there is a way for the images to remain using the blob, we can keep it.
> 
> can you can share me a repo, it will easy to debug

Yes, one moment that i go to send.

**Comment by JohnnyDevJs** [comment]
> > > > > > I'm new to programming, could you help me? Return the image in base64.
> > > > > 
> > > > > 
> > > > > do you have an API to upload image files?
> > > > 
> > > > 
> > > > yes I have.
> > > 
> > > 
> > > I noticed that when I load and save content the image remains for a while and then disappears. using the blob, if there is a way for the images to remain using the blob, we can keep it.
> > 
> > 
> > can you can share me a repo, it will easy to debug
> 
> Yes, one moment that i go to send.


The repo is private, I can't send it to you

**Comment by hunghg255** [comment]
> > > > > > > I'm new to programming, could you help me? Return the image in base64.
> > > > > > 
> > > > > > 
> > > > > > do you have an API to upload image files?
> > > > > 
> > > > > 
> > > > > yes I have.
> > > > 
> > > > 
> > > > I noticed that when I load and save content the image remains for a while and then disappears. using the blob, if there is a way for the images to remain using the blob, we can keep it.
> > > 
> > > 
> > > can you can share me a repo, it will easy to debug
> > 
> > 
> > Yes, one moment that i go to send.
> 
> The repo is private, I can't send it to you

so you can use extension `ImageUpload`
convert file to base64, you can check this link
https://stackoverflow.com/questions/36280818/how-to-convert-file-to-base64-in-javascript

**Comment by JohnnyDevJs** [comment]
> so you can use extension `ImageUpload`
> convert file to base64, you can check this link

Look my code:

`ImageUpload.configure({
    upload: (file: File) => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          const reader = new FileReader()
          reader.readAsDataURL(file)
          reader.onload = () => resolve(reader.result as string)
          reader.onerror = (error) => reject(error)
        }, 500)
      })
    },
  })`

**Comment by JohnnyDevJs** [comment]
> > so you can use extension `ImageUpload`
> > convert file to base64, you can check this link
> 
> Look my code:
> 
> `ImageUpload.configure({ upload: (file: File) => { return new Promise((resolve, reject) => { setTimeout(() => { const reader = new FileReader() reader.readAsDataURL(file) reader.onload = () => resolve(reader.result as string) reader.onerror = (error) => reject(error) }, 500) }) }, })`
> 
> Correct?

Is correct!

<img width="924" alt="Captura de Tela 2024-10-01 às 13 59 00" src="https://github.com/user-attachments/assets/e11b7a8e-ab5d-48d9-9a3a-9d0135081d58">

Great, thank you!

**Comment by hunghg255** [comment]
yes look so good
