### ISSUE TITLE
Modify button submits form

### ISSUE THREAD

**Issue by stefan-krajnik** [hunghg255/reactjs-tiptap-editor#54]
If the editor is inside a `form` a click in the button (see screenshot) , submits the form
<img width="113" alt="Screenshot 2024-10-04 at 6 43 35 PM" src="https://github.com/user-attachments/assets/beae1e1f-396e-418f-9500-8648822dab93">

Either `preventDefault` or add `type="button"` to the button component.

**Comment by hunghg255** [comment]
> If the editor is inside a `form` a click in the button (see screenshot) , submits the form <img alt="Screenshot 2024-10-04 at 6 43 35 PM" width="113" src="https://private-user-images.githubusercontent.com/16229997/373823119-beae1e1f-396e-418f-9500-8648822dab93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTEyMzMsIm5iZiI6MTcyODA5MDkzMywicGF0aCI6Ii8xNjIyOTk5Ny8zNzM4MjMxMTktYmVhZTFlMWYtMzk2ZS00MThmLTk1MDAtODY0ODgyMmRhYjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDAxMTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ODQzOTdkMzkxZjUxMjdmYTM4YmNmOGMzOGM0NGRjNGEyMzkyMmMxOTM5M2E5ZGQxN2VjNGQxMTA2ZmIwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xV71Z0oI3LULHcKRclhoxe-LQ36ubrEhwmzsEbbM2Os">
> 
> Either `preventDefault` or add `type="button"` to the button component.

oke, I got it. I will check this
or welcome your contribute
