### ISSUE TITLE
Nextjs error - SyntaxError: Named export 'saveAs' not found. The requested module 'file-saver' is a CommonJS module

### ISSUE THREAD

**Issue by stefan-krajnik** [hunghg255/reactjs-tiptap-editor#58]
<img width="987" alt="Screenshot 2024-10-07 at 3 32 05 PM" src="https://github.com/user-attachments/assets/5692a27b-3d85-48a3-b3d9-3615922e5a80">

Using dynamic import is not a solution, I need to be able to import extentions to generate html from JSON on server.

**Comment by hunghg255** [comment]
@stefan-krajnik how to can you get this error? can you share a repo?

**Comment by stefan-krajnik** [comment]
@hunghg255 I don't have it anywhere publicly available, but it's easy to reproduce.

If you import the editor anywhere where it runs on server, e.g. `pages/*` or `pages/api/*` it crashes. 
It only works if I separate it to a component which is then `dynamic`ally imported.

`next 14.2.13`

**Comment by stefan-krajnik** [comment]
The issue is here 
https://github.com/hunghg255/reactjs-tiptap-editor/blob/5b0b4aa21ab5539c4c3eb464d7c825f01da05180/src/extensions/ExportWord/ExportWord.ts#L2

I'd recommend either to use another package or import the package asynchronously when save is triggered

So here
https://github.com/hunghg255/reactjs-tiptap-editor/blob/5b0b4aa21ab5539c4c3eb464d7c825f01da05180/src/extensions/ExportWord/ExportWord.ts#L65-L67

I'd do something like
```
const fileSaver = await import('file-saver')
const wordDocument = docxSerializer.serialize(editor.state.doc, opts) 
Packer.toBlob(wordDocument).then(blob => fileSaver.saveAs(new Blob([blob]), 'document.docx')) 
return true 
```

You can do the same even if you decide to use different library for saving files, it doesn't need to be part of the main bundle

**Comment by hunghg255** [comment]
> The issue is here
> 
> https://github.com/hunghg255/reactjs-tiptap-editor/blob/5b0b4aa21ab5539c4c3eb464d7c825f01da05180/src/extensions/ExportWord/ExportWord.ts#L2
> 
> I'd recommend either to use another package or import the package asynchronously when save is triggered
> 
> So here
> 
> https://github.com/hunghg255/reactjs-tiptap-editor/blob/5b0b4aa21ab5539c4c3eb464d7c825f01da05180/src/extensions/ExportWord/ExportWord.ts#L65-L67
> 
> I'd do something like
> 
> ```
> const fileSaver = await import('file-saver')
> const wordDocument = docxSerializer.serialize(editor.state.doc, opts) 
> Packer.toBlob(wordDocument).then(blob => fileSaver.saveAs(new Blob([blob]), 'document.docx')) 
> return true 
> ```
> 
> You can do the same even if you decide to use different library for saving files, it doesn't need to be part of the main bundle

oke, I got it, I will check late-night

**Comment by stefan-krajnik** [comment]
@hunghg255 any progress?

**Comment by stefan-krajnik** [comment]
@hunghg255 any progress?

**Comment by hunghg255** [comment]
> @hunghg255 any progress?

 try config `next.config.js`
```
const nextConfig = {
  transpilePackages: ['shiki'],
};
```
