### ISSUE TITLE
[Bug] Popover is not working with Dialog Shadcn due to the overlay issue

### ISSUE THREAD

**Issue by phongphanh** [hunghg255/reactjs-tiptap-editor#69]
Cannot click on popover when using **RichTextEditor** on Dialog Shadcn:
- LinkEditPopover
- Table
- ...

**Comment by hunghg255** [comment]
@phongphanh maybe related to this issue. I will check this later
https://github.com/shadcn-ui/ui/issues/1511

**Comment by hunghg255** [comment]
@phongphanh I fixed this issue. let try latest version
