### ISSUE TITLE
[Bug] Could not resolve "y-prosemirror"

### ISSUE THREAD

**Issue by lqminh2207** [hunghg255/reactjs-tiptap-editor#70]
I got this bug when follow basic installation

![image](https://github.com/user-attachments/assets/c893ef3f-78c7-4afa-98f7-27dd08389a86)

![image](https://github.com/user-attachments/assets/2bc5e9a4-d2af-43bd-96d5-884296d1ddff)

```
import { useState } from 'react';

import RichTextEditor, { BaseKit } from 'reactjs-tiptap-editor';
import 'reactjs-tiptap-editor/style.css';

const extensions = [
  BaseKit.configure({
    // Show placeholder
    placeholder: {
      showOnlyCurrent: true,
    },

    // Character count
    characterCount: {
      limit: 50_000,
    },
  }),
];

const DEFAULT = '';

export default function RichTextExample() {
  const [content, setContent] = useState(DEFAULT);

  const onChangeContent = (value: any) => {
    setContent(value);
  };

  return (
    <RichTextEditor
      output="html"
      content={content}
      extensions={extensions}
      onChangeContent={onChangeContent}
    />
  );
}
```

**Comment by hunghg255** [comment]
@lqminh2207 Hi, you can resolve to install `y-prosemirror`
I will check this bug

**Comment by lqminh2207** [comment]
@hunghg255 It seem that repo is not public 

![image](https://github.com/user-attachments/assets/770cf499-6484-427a-8e5d-92dcbf17652d)

**Comment by hunghg255** [comment]
@lqminh2207 maybe you need to move use npm or pnpm
because that library is not yet available on yarn
