### ISSUE TITLE
Allowing the Image to crop

### ISSUE THREAD

**Issue by MeDeveloperWeb** [hunghg255/reactjs-tiptap-editor#71]
The functionality for cropping the image before uploading it would be awesome. For now, I want to be able to customize the image (crop it) before running the `onUpload` function. Is there a way to achieve that?

Btw, Awesome Project!!

**Comment by hunghg255** [comment]
@MeDeveloperWeb thanks for the feedback,
your question is a great feature, I will consider making a new extension for crop image
