### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by lqminh2207** [hunghg255/reactjs-tiptap-editor#72]
When typing continuously, it has to re-render too much, leading to performance issues, very slow, lag.

**Comment by lqminh2207** [comment]
Another issue, when I try to deploy my project to netlify. After install your package, it takes a long time to build and leads to out of memory, and cannot deploy anymore

![image](https://github.com/user-attachments/assets/7fdf44c0-999d-486f-a43d-3f22a4c82548)

**Comment by hunghg255** [comment]
> Another issue, when I try to deploy my project to netlify. After install your package, it takes a long time to build and leads to out of memory, and cannot deploy anymore
> 
> ![image](https://private-user-images.githubusercontent.com/93562814/376994875-7fdf44c0-999d-486f-a43d-3f22a4c82548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzUxMjMsIm5iZiI6MTcyOTA3NDgyMywicGF0aCI6Ii85MzU2MjgxNC8zNzY5OTQ4NzUtN2ZkZjQ0YzAtOTk5ZC00ODZmLWE0M2QtM2YyMmE0YzgyNTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEwMzM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMmJmYTc0ODAyYTMyMTUyZWFhMzBlNzY1NzFlZGI3NzcxOTNlOTZlMDc4MjBhYzUxODYyYjA5NmQ0M2IyNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DSc-0r8PrpYIJH0UisvqZD15J8XEqNd_v31xTVnsJY0)

you need to use npm instead yarn
send me a repo your component, I can check help me

**Comment by lqminh2207** [comment]
@hunghg255 https://github.com/SE-Capstone/FE 
Please help me

**Comment by hunghg255** [comment]
> @hunghg255 [SE-Capstone/FE](https://github.com/SE-Capstone/FE) Please help me check

```
export default function RichTextExample() {
  const [content, setContent] = useState(DEFAULT);

  const onChangeContent = (value: any) => {
    setContent(value);
  };

  return (
    <Container mt={5}>
      <RichTextEditor
        dark={false}
        label="Editor"
        output="html"
        content={DEFAULT}
        extensions={extensions}
        onChangeContent={onChangeContent}
      />
    </Container>
  );
}

```
the content should use default value instead use the value from state

**Comment by hunghg255** [comment]
like be you see from your image error. it still use yarn

Vào Th 4, 16 thg 10, 2024 lúc 18:15 xkrystall ***@***.***> đã
viết:

**Comment by hunghg255** [comment]
let try to remove file yarn.lock on your repo

Vào Th 4, 16 thg 10, 2024 lúc 18:16 Hung Hoang ***@***.***> đã
viết:

**Comment by salaarkhan-dev** [comment]
Add these two configuation in your Component:

```
<RcTiptapEditor
        ref={refEditor}
        output='html'
        content={DEFAULT}
        onChangeContent={onValueChange}
        extensions={extensions}
        disabled={disable}
        // Add these options
        useEditorOptions={{
          immediatelyRender: true,
          shouldRerenderOnTransaction: false,
        }}
       
      />
```
