### ISSUE TITLE
[Fix] CodeBlock list scroll

### ISSUE THREAD

**Issue by Markkop** [hunghg255/reactjs-tiptap-editor#74]
![image](https://github.com/user-attachments/assets/cd22e0dc-45e5-47de-bbab-9242e50b8144)

I can reproduce the issue on Playground with a really big zoom to force the container out of the screen

![image](https://github.com/user-attachments/assets/a02a99ac-9154-4b83-94a1-77e87346c653)

**Comment by hunghg255** [comment]
@Markkop thank for contribute. I will test later
