### ISSUE TITLE
[Bug] Could not resolve "y-prosemirror"

### ISSUE THREAD

**Issue by stefan-krajnik** [hunghg255/reactjs-tiptap-editor#76]
Reopen of https://github.com/hunghg255/reactjs-tiptap-editor/issues/70

The issue is still present `y-prosemirror` is not installed and neither are its peerDependencies. 
I was getting errors about missing `yjs` and `y-protocols` so I had to install of of them manually.

**Comment by hunghg255** [comment]
@stefan-krajnik I am not sure about this issue, Im using pnpm, and it work normally

**Comment by phuctranngh** [comment]
I met this problem as well

**Comment by hunghg255** [comment]
@phuctranngh this issue is related to yarn, I fixed this, you can install the latest
