### ISSUE TITLE
[Feat] Inline content

### ISSUE THREAD

**Issue by TungNguyen-C4U** [hunghg255/reactjs-tiptap-editor#79]
This feature will help us to use the inline palette to add images, links, math & TeX, and more. 

The inline palette let’s you quickly add extra content to your text block without create new line (currently we cannot add KaTex formula or image in the same line but rather it return to new line). Simply hit `/` on any text block to open the inline palette.

**Comment by hunghg255** [comment]
- [x] Inline Katex
- [ ] Inline Image
