### ISSUE TITLE
[Feat] Add more supported languages in CodeBlock component

### ISSUE THREAD

**Issue by TungNguyen-C4U** [hunghg255/reactjs-tiptap-editor#82]
Hi,
Currently I found that the codeblock component support quite few languages (only HTML, CSS, JS, Bash). Some popular languages like SQL, JSON, XML .. had not been supported! 
Can you add more please since the [lowlight library](https://github.com/wooorm/lowlight) which was used in Tiptap support so many coding lanaguages

**Comment by hunghg255** [comment]
@TungNguyen-C4U Hi, I understand what you mean, lowlight is recommended from tiptap docs
But I integrated another lib use [Shiki](https://shiki.style/guide/) 

you can config your language from configure
```ts
 CodeBlock.configure({
    defaultTheme: 'dracula',
    languages: ['javascript', 'typescript', 'bash', 'json', 'html', 'css', 'markdown', 'sql', 'xml']
  }),
  ```
<img width="948" alt="Screenshot 2024-10-21 at 15 08 41" src="https://github.com/user-attachments/assets/3c7e2e42-454b-4fb1-bdab-1ab0bc926ad5">

**Comment by TungNguyen-C4U** [comment]
@hunghg255 Hello
It is quite a long when your library has been update and I can not find where to setup new other supported language like before. Can you please show me where to update the list input new languages of CodeBlock now?
