### ISSUE TITLE
How change dark mode color to Like Black, bg-gray-950

### ISSUE THREAD

**Issue by mishraasaurabh** [hunghg255/reactjs-tiptap-editor#87]
i have not found any for change bg-color

**Comment by mishraasaurabh** [comment]
I have added custom css style.css

:root {
    --richtext-bg-color: gray;   /* Light background */
    --richtext-border-color: gray; /* Light border color */
    --outline-color :red;
}

body.dark {
    --richtext-bg-color: red;
    --richtext-border-color: 60, 60, 160;
    --outline-color :red;
}

.richtext-outline{
    border-color: white !important;
    /*outline-style: none !important;*/
}

.richtext-outline-1{
    outline-width: 1px !important;
    outline-color: hsl(var(--outline-color) / 1) !important;

    border: 1px solid hsl(var(--richtext-border-color) / 1) !important;
}

.richtext-bg-background, .reactjs-tiptap-editor {
    background-color: hsl(var(--richtext-bg-color) / 1) !important;
}

can you help me pls

i am using vite react typescript with tailwind css

**Comment by hunghg255** [comment]
@mishraasaurabh Im using color hls, so you need to set value is hls
check this file https://github.com/hunghg255/reactjs-tiptap-editor/blob/ec29cb37a8a10fcf16b9aa4bb231a733ee351ca1/src/styles/global.scss#L5
