### ISSUE TITLE
Hydration error in nextjs form with server action

### ISSUE THREAD

**Issue by Allacher** [hunghg255/reactjs-tiptap-editor#98]
When I use this editor in combination with react hook forms in a form which gets submitted with a nextjs server action I always get a SSR hydration error. 
After a lot of debugging I found out that the problem is cased by the css import. 

My fix was copying the styles into my project and removing all font imports. Somehow this fixed the problem.

**Comment by hunghg255** [comment]
@Allacher thank you for feedback,

**Comment by hunghg255** [comment]
@Allacher try config `next.config.js`
```
const nextConfig = {
  transpilePackages: ['shiki'],
};
```
