### ISSUE TITLE
Mark a text as link submits the form

### ISSUE THREAD

**Issue by waleedsalah4** [hunghg255/reactjs-tiptap-editor#99]
I am using the editor inside a form (using formik to manage the form), and trying to mark a text as link like this:
![image](https://github.com/user-attachments/assets/af3984f0-c241-4133-916f-871d30b416b5)
 then hit the apply button it submits the form as its type is "submit" which isn't the desired behavior
 so how to fix this or disable this from submitting the entire form ??

**Comment by hunghg255** [comment]
@waleedsalah4 thanks for feedback, I will check this later

**Comment by kurian86** [comment]
The same thing happens with the 'Apply' button in the image extension when an image is added from a URL.

**Comment by waleedsalah4** [comment]
If i have a link and select it to edit it like this

![Image](https://github.com/user-attachments/assets/884e01d9-9499-453f-8a00-3567165d8121)
The box that contain the pencil icon shows and clicking it show this popup to edit the link in it

![Image](https://github.com/user-attachments/assets/38361a58-68db-4da7-9578-e9144ff10771)
the `apply` button also submits the entire form and it has type submit

Please check this also.

**Comment by M4rdine** [comment]
> If i have a link and select it to edit it like this
> 
> ![Image](https://github.com/user-attachments/assets/884e01d9-9499-453f-8a00-3567165d8121) The box that contain the pencil icon shows and clicking it show this popup to edit the link in it
> 
> ![Image](https://github.com/user-attachments/assets/38361a58-68db-4da7-9578-e9144ff10771) the `apply` button also submits the entire form and it has type submit
> 
> Please check this also.

same here
